[pytest]
DJANGO_SETTINGS_MODULE = university_activities.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --tb=short
    --cov=core
    --cov-report=html
    --cov-report=term-missing
