# Generated by Django 4.2.7 on 2025-11-21 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=100)),
                ("available_slots", models.IntegerField(default=50)),
                ("registered_count", models.IntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "activities",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "username",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=200, unique=True),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("type", models.CharField(default="info", max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        fields=["user"], name="notificatio_user_id_e78525_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_e4c995_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("activity_name", models.CharField(blank=True, max_length=200)),
                ("activity_code", models.CharField(blank=True, max_length=100)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="قيد الانتظار", max_length=50)),
                ("response_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to="core.user",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "employee_requests",
                "indexes": [
                    models.Index(
                        fields=["employee"], name="employee_re_employe_6ccd85_idx"
                    ),
                    models.Index(
                        fields=["student"], name="employee_re_student_996425_idx"
                    ),
                    models.Index(
                        fields=["status"], name="employee_re_status_4ff3e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                ("activity_type", models.CharField(max_length=100)),
                ("activity_number", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=200)),
                ("specialization", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50)),
                ("details", models.TextField(blank=True)),
                ("status", models.CharField(default="قيد الانتظار", max_length=50)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "indexes": [
                    models.Index(
                        fields=["submitted_at"], name="application_submitt_f3e3d7_idx"
                    ),
                    models.Index(
                        fields=["user"], name="application_user_id_47c703_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="مسجل", max_length=50)),
                (
                    "registered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_registrations",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "activity_registrations",
                "indexes": [
                    models.Index(
                        fields=["activity"], name="activity_re_activit_c9232c_idx"
                    ),
                    models.Index(
                        fields=["user"], name="activity_re_user_id_4e9fa3_idx"
                    ),
                ],
                "unique_together": {("activity", "user")},
            },
        ),
    ]
