# Generated by Django 4.2.7 on 2025-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="project_file",
            field=models.FileField(blank=True, null=True, upload_to="project_files/"),
        ),
    ]
