# Generated by Django 4.2.7 on 2025-12-03 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_application_project_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="message_files/"),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.application",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="core.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "indexes": [
                    models.Index(
                        fields=["application"], name="messages_applica_b51119_idx"
                    ),
                    models.Index(fields=["sender"], name="messages_sender__6ae55a_idx"),
                    models.Index(
                        fields=["receiver"], name="messages_receive_432d39_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="messages_created_919c58_idx"
                    ),
                ],
            },
        ),
    ]
