# Generated by Django 4.2 on 2026-04-20 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_employeedirectmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="employeedirectmessage",
            new_name="employee_di_sender__89afb9_idx",
            old_name="core_employ_sender__f5e192_idx",
        ),
        migrations.RenameIndex(
            model_name="employeedirectmessage",
            new_name="employee_di_receive_746126_idx",
            old_name="core_employ_receiver_f03e8b_idx",
        ),
        migrations.RenameIndex(
            model_name="employeedirectmessage",
            new_name="employee_di_created_8e7e16_idx",
            old_name="core_employ_created_82782e_idx",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "super_employee")),
                fields=("role",),
                name="unique_super_employee",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="core.user",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["is_active"], name="announcemen_is_acti_8058e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["created_at"], name="announcemen_created_cc79cd_idx"
            ),
        ),
    ]
