# Generated by Django 4.2 on 2026-04-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_announcement_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["is_active"], name="activities_is_acti_cff4bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["start_date"], name="activities_start_d_fe1952_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["category"], name="activities_categor_1d724e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="application_status_e61111_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["user", "status"], name="application_user_id_4cfcce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
    ]
