# Generated by Django 4.2.7 on 2026-05-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_system_notification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_super_employee',
        ),
    ]
