# Generated by Django 4.2.7 on 2026-05-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_unique_super_employee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'super_employee')), fields=('role',), name='unique_super_employee'),
        ),
    ]
