# Generated by Django 4.2.7 on 2026-05-12 23:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_unique_super_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(default='general', max_length=100)),
                ('request_message', models.TextField(default='أرغب في الانضمام للأنشطة الطلابية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to='core.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='core.user')),
            ],
            options={
                'db_table': 'student_join_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='student_joi_student_e2b5d4_idx'), models.Index(fields=['status'], name='student_joi_status_45f172_idx'), models.Index(fields=['created_at'], name='student_joi_created_6c286a_idx'), models.Index(fields=['activity_type'], name='student_joi_activit_32a004_idx')],
            },
        ),
    ]
