# Generated by Django 4.2.7 on 2026-05-13 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studentjoinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('general', 'عام'), ('contest', 'مسابقة'), ('study', 'دراسة'), ('announcement', 'إعلانات'), ('private', 'خاص'), ('support', 'دعم فني'), ('project', 'مشروع')], default='general', max_length=50)),
                ('privacy', models.CharField(choices=[('public', 'عام'), ('private', 'خاص'), ('invite-only', 'دعوة فقط')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('archived', 'مؤرشف')], default='active', max_length=20)),
                ('max_members', models.IntegerField(default=50)),
                ('rules', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('message_retention', models.CharField(default='forever', max_length=20)),
                ('file_sharing', models.CharField(default='enabled', max_length=20)),
                ('max_file_size', models.IntegerField(default=10485760)),
                ('allowed_file_types', models.TextField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('encryption_enabled', models.BooleanField(default=False)),
                ('auto_mod_enabled', models.BooleanField(default=True)),
                ('read_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chat_rooms', to='core.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_rooms', to='core.user')),
            ],
            options={
                'db_table': 'chat_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('file', 'ملف'), ('system', 'نظام')], default='text', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatroom')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.chatmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent_messages', to='core.user')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('moderator', 'مشرف'), ('member', 'عضو')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_memberships', to='core.user')),
            ],
            options={
                'db_table': 'chat_room_members',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['chat_room'], name='chat_room_m_chat_ro_3b7fcd_idx'), models.Index(fields=['user'], name='chat_room_m_user_id_9c7e42_idx'), models.Index(fields=['role'], name='chat_room_m_role_35f395_idx'), models.Index(fields=['joined_at'], name='chat_room_m_joined__9ee400_idx')],
                'unique_together': {('chat_room', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_by'], name='chat_rooms_created_6584b2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['admin'], name='chat_rooms_admin_i_2dbf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['type'], name='chat_rooms_type_d1942a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['privacy'], name='chat_rooms_privacy_707bce_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['status'], name='chat_rooms_status_0c6d66_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_at'], name='chat_rooms_created_108bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_activity'], name='chat_rooms_last_ac_5e6dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room'], name='chat_messag_chat_ro_adc143_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='chat_messag_sender__e8b05b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='chat_messag_message_b8fb34_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_messag_created_eb4133_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['reply_to'], name='chat_messag_reply_t_8befc9_idx'),
        ),
    ]
