# Generated by Django 4.2.7 on 2026-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chatroom_chatmessage_chatroommember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='contest_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
