# Generated by Django 4.2.7 on 2026-05-30 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chatroom_contest_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_pinned'], name='chat_messag_is_pinn_f2f5de_idx'),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='core.user')),
            ],
            options={
                'db_table': 'message_reactions',
                'indexes': [
                    models.Index(fields=['message'], name='message_rea_messa_3fb393_idx'),
                    models.Index(fields=['user'], name='message_rea_user_id_565363_idx'),
                    models.Index(fields=['emoji'], name='message_rea_emoji_2c473a_idx'),
                ],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='core.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='core.user')),
            ],
            options={
                'db_table': 'typing_indicators',
                'indexes': [
                    models.Index(fields=['chat_room'], name='typing_indi_chat_ro_f7c35b_idx'),
                    models.Index(fields=['user'], name='typing_indi_user_id_752829_idx'),
                    models.Index(fields=['last_updated'], name='typing_indi_last_up_ad336b_idx'),
                ],
                'unique_together': {('chat_room', 'user')},
            },
        ),
    ]
