# Generated by Django 4.2.7 on 2026-05-16 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chatroom_contest_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='contest_details',
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('academic', 'أكاديمية'), ('sports', 'رياضية'), ('art', 'فنية'), ('technology', 'تقنية'), ('general', 'عامة'), ('creative', 'إبداعية')], default='general', max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('eligibility', models.JSONField(default=list)),
                ('requirements', models.TextField()),
                ('max_participants', models.IntegerField(default=50)),
                ('prize', models.TextField(blank=True, null=True)),
                ('rules', models.TextField()),
                ('judges', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('upcoming', 'قادمة'), ('completed', 'مكتملة')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'عامة'), ('private', 'خاصة'), ('restricted', 'مقيدة')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to='core.user')),
            ],
            options={
                'db_table': 'contests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by'], name='contests_created_d3535b_idx'), models.Index(fields=['type'], name='contests_type_d97b60_idx'), models.Index(fields=['status'], name='contests_status_13568f_idx'), models.Index(fields=['visibility'], name='contests_visibil_d06968_idx'), models.Index(fields=['start_date'], name='contests_start_d_658293_idx'), models.Index(fields=['end_date'], name='contests_end_dat_3abbe8_idx'), models.Index(fields=['created_at'], name='contests_created_70d368_idx')],
            },
        ),
    ]
