# Generated by Django 4.2.7 on 2026-05-17 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_chatroom_contest_details_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('general', 'عام'), ('educational', 'تعليمي'), ('announcement', 'إعلان'), ('tutorial', 'دليل'), ('entertainment', 'ترفيهي')], default='general', max_length=20)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'عام'), ('private', 'خاص'), ('students_only', 'للطلاب فقط')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_videos', to='core.user')),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by'], name='videos_created_4da641_idx'), models.Index(fields=['category'], name='videos_categor_f65164_idx'), models.Index(fields=['status'], name='videos_status_510af8_idx'), models.Index(fields=['visibility'], name='videos_visibil_a7c414_idx'), models.Index(fields=['created_at'], name='videos_created_f84293_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_posts/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_posts', to='core.user')),
            ],
            options={
                'db_table': 'student_posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author'], name='student_pos_author__1449b8_idx'), models.Index(fields=['created_at'], name='student_pos_created_88994e_idx'), models.Index(fields=['is_active'], name='student_pos_is_acti_91f807_idx')],
            },
        ),
    ]
